---

- name: Set common fact for tasks
  set_fact:
    server_url: "{{ jellyfin_api_url | replace(jellyfin_http_port, '8096') }}"

- name: Set metadata language preferences
  uri:
    url: "{{ server_url }}/Startup/Configuration"
    method: POST
    body:
      UICulture: "{{ jellyfin_ui_culture }}"
      MetadataCountryCode: "{{ jellyfin_metadata_country_code }}"
      PreferredMetadataLanguage: "{{ jellyfin_metadata_language }}"
    body_format: json
    headers:
      Accept: application/json
      Content-Type: application/json
    status_code: 204
  changed_when: true

- name: Trigger intial user creation
  uri:
    url: "{{ server_url }}/Startup/User"
    method: GET
    headers:
      Accept: application/json
    status_code: 200
  changed_when: true

- name: Set initial user's name
  no_log: "{{ not jellyfin_debug_logging | bool }}"
  uri:
    url: "{{ server_url }}/Startup/User"
    method: POST
    body:
      Name: "{{ jellyfin_admin_username }}"
    body_format: json
    headers:
      Accept: application/json
      Content-Type: application/json
    status_code: 204
  register: result
  changed_when: true

- name: Set initial user's password
  no_log: "{{ not jellyfin_debug_logging | bool }}"
  uri:
    url: "{{ server_url }}/Startup/User"
    method: POST
    body:
      Password: "{{ jellyfin_admin_password }}"
    body_format: json
    headers:
      Accept: application/json
      Content-Type: application/json
    status_code: 204
  register: result
  changed_when: true

- name: Enable/disable remote access
  uri:
    url: "{{ server_url }}/Startup/User"
    method: POST
    body:
      EnableRemoteAccess: "{{ jellyfin_remote_access }}"
    body_format: json
    headers:
      Accept: application/json
      Content-Type: application/json
    status_code: 204
  changed_when: true

- name: Enable/disable automatic port mapping
  uri:
    url: "{{ server_url }}/Startup/User"
    method: POST
    body:
      EnableAutomaticPortMapping: "{{ jellyfin_automatic_port_mapping }}"
    body_format: json
    headers:
      Accept: application/json
      Content-Type: application/json
    status_code: 204
  changed_when: true

- name: Finish wizard
  uri:
    url: "{{ server_url }}/Startup/Complete"
    method: POST
    headers:
      Accept: "application/json"
    status_code: 204
  changed_when: true
